const MenuData = {
  Pizza: [
    {
      id: 1,
      title: "Pizza Margherita",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/pizza/margarita.avif",
      originalPrice: "25.89DH",
      discountedPrice: "19.99",
    },
    {
      id: 2,
      title: "Pizza Viande Hacher",
      description: "Loaded with spicy pepperoni and melted cheese.",
      image: "src/assets/pizza/viande4.jpg",
      originalPrice: "35.89DH",
      discountedPrice: "29.89",
    },
    {
      id: 3,
      title: "Pizza Poulet",
      description: "Topped with fresh veggies and creamy cheese.",
      image: "src/assets/pizza/poulet1.webp",
      originalPrice: "35.89DH",
      discountedPrice: "29.89",
    },
    {
      id: 4,
      title: "Pizza Vegetarienne",
      description: "Topped with fresh veggies and creamy cheese.",
      image: "src/assets/pizza/vegetarienne1.jpg",
      originalPrice: "35.89DH",
      discountedPrice: "29.89",
    },
    {
      id: 5,
      title: "Pizza Thon",
      description: "Topped with fresh veggies and creamy cheese.",
      image: "src/assets/pizza/thon1.jpg",
      originalPrice: "35.89DH",
      discountedPrice: "29.89",
    },
    {
      id: 6,
      title: "Pizza SeaFood",
      description: "Topped with fresh veggies and creamy cheese.",
      image: "src/assets/pizza/sea.webp",
      originalPrice: "35.89DH",
      discountedPrice: "29.89",
    },
    {
      id: 7,
      title: "Pizza 4 Seasons",
      description: "Topped with fresh veggies and creamy cheese.",
      image: "src/assets/pizza/4sea.jpg",
      originalPrice: "40.00DH",
      discountedPrice: "34.99",
    },
    {
      id: 8,
      title: "Pizza Special",
      description: "Topped with fresh veggies and creamy cheese.",
      image: "src/assets/pizza/special1.png",
      originalPrice: "40.00DH",
      discountedPrice: "34.99",
    },
  ],
  Salades: [
    {
      id: 1,
      title: "Salades Marocaine",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/salade/Salade_marocaine.jpeg",
      originalPrice: "15.45DH",
      discountedPrice: "09.99DH",
    },
    {
      id: 2,
      title: "Salades Necoise",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/salade/nicoise.jpeg",
      originalPrice: "18.45DH",
      discountedPrice: "14.99DH",
    },
    {
      id: 3,
      title: "Salades Pates",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/salade/pate1.jpeg",
      originalPrice: "25.05DH",
      discountedPrice: "19.99DH",
    },
    {
      id: 4,
      title: "Salades Riche",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/salade/riche1.jpg",
      originalPrice: "25.05DH",
      discountedPrice: "19.99DH",
    },
    {
      id: 5,
      title: "Salades Chef",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/salade/chef.jpg",
      originalPrice: "35.44DH",
      discountedPrice: "24.99DH",
    },
    {
      id: 6,
      title: "Salades Precheur",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/salade/precheur.jpeg",
      originalPrice: "25.65DH",
      discountedPrice: "29.89DH",
    },
  ],
  Panini: [
    {
      id: 1,
      title: "Panini Omlette",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/panini/omom.jpg",
      originalPrice: "20.05DH",
      discountedPrice: "15.99DH",
    },
    {
      id: 2,
      title: "Panini Viande hache",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/panini/viand hache.jpg",
      originalPrice: "23.45DH",
      discountedPrice: "19.99DH",
    },
    {
      id: 3,
      title: "Panini Poulet",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/panini/-poulet-.jpeg",
      originalPrice: "23.45DH",
      discountedPrice: "19.99DH",
    },
    {
      id: 4,
      title: "Panini Sauccise",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/panini/saucisse.jpeg",
      originalPrice: "23.45DH",
      discountedPrice: "19.99DH",
    },
    {
      id: 5,
      title: "Panini Thon",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/panini/THON.jpg",
      originalPrice: "23.45DH",
      discountedPrice: "19.99DH",
    },
    {
      id: 6,
      title: "Panini Mixte",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/panini/mixte.jpg",
      originalPrice: "29.65DH",
      discountedPrice: "24.89DH",
    },
    {
      id: 7,
      title: "Panini Fruits de mer",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/panini/seaFood.jpg",
      originalPrice: "35.75DH",
      discountedPrice: "29.89DH",
    },
  ],
  Cosamia: [
    {
      id: 1,
      title: "Cosamia Viande Hache",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/Cosamia/viande hacher.png",
      originalPrice: "25.45DH",
      discountedPrice: "19.99DH",
    },
    {
      id: 2,
      title: "Cosamia Poulet",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/Cosamia/viande hacher.png",
      originalPrice: "23.45DH",
      discountedPrice: "19.99DH",
    },
    {
      id: 3,
      title: "Cosamia Saussice",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/Cosamia/viande hacher.png",
      originalPrice: "23.45DH",
      discountedPrice: "19.99DH",
    },
    {
      id: 4,
      title: "Cosamia Thon",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/Cosamia/viande hacher.png",
      originalPrice: "23.45DH",
      discountedPrice: "19.99DH",
    },
    {
      id: 5,
      title: "Cosamia Mixte",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/Cosamia/viande hacher.png",
      originalPrice: "30.45DH",
      discountedPrice: "24.99DH",
    },
    {
      id: 6,
      title: "Cosamia Fruites d'mer ",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/Cosamia/viande hacher.png",
      originalPrice: "25.65DH",
      discountedPrice: "29.89DH",
    },
  ],
  Sandwish: [
    {
      id: 1,
      title: "Sandwish Omlette",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/Sandwish/omlette.jpeg",
      originalPrice: "15.45DH",
      discountedPrice: "09.99DH",
    },
    {
      id: 2,
      title: "Sandwish Viande Hache",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/Sandwish/viande hacher.jpeg",
      originalPrice: "18.45DH",
      discountedPrice: "14.99DH",
    },
    {
      id: 3,
      title: "Sandwish Poulet",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/Sandwish/poulet.jpeg",
      originalPrice: "18.45DH",
      discountedPrice: "14.99DH",
    },
    {
      id: 4,
      title: "Sandwish Saucisse",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/Sandwish/Saucisse.jpeg",
      originalPrice: "18.45DH",
      discountedPrice: "14.90DH",
    },
    {
      id: 5,
      title: "Sandwish Thon",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/Sandwish/thon.jpeg",
      originalPrice: "18.45DH",
      discountedPrice: "14.90DH",
    },
    {
      id: 6,
      title: "Sandwish Sea Food",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/Sandwish/seafood.webp",
      originalPrice: "29.65DH",
      discountedPrice: "24.89DH",
    },
  ],
  Burger: [
    {
      id: 1,
      title: "Burger Chesse",
      description: "Fresh Plats, basil, and tomato sauce.",
      image: "src/assets/Burger/cheese.jpeg",
      originalPrice: "22.45DH",
      discountedPrice: "19.99DH",
    },
    {
      id: 2,
      title: "Burger Chiken",
      description: "Fresh Poulet, basil, and tomato sauce.",
      image: "src/assets/Burger/chiken.jpeg",
      originalPrice: "22.45DH",
      discountedPrice: "19.99DH",
    },
  ],
  Tacos: [
    {
      id: 1,
      title: "Tacos Viande hacher",
      description: "Fresh Plats, basil, and tomato sauce.",
      image: "src/assets/Tacos/Viand hacher.jpeg",
      originalPrice: "29.45DH",
      discountedPrice: "24.99DH",
    },
    {
      id: 2,
      title: "Tacos Chiken",
      description: "Fresh Poulet, basil, and tomato sauce.",
      image: "src/assets/Tacos/poulet.avif",
      originalPrice: "29.45DH",
      discountedPrice: "25.04DH",
    },
    {
      id: 3,
      title: "Tacos Saucisse",
      description: "Fresh Poulet, basil, and tomato sauce.",
      image: "src/assets/Tacos/saucisse.avif",
      originalPrice: "29.45DH",
      discountedPrice: "25.04DH",
    },
    {
      id: 4,
      title: "Tacos Thon",
      description: "Fresh Poulet, basil, and tomato sauce.",
      image: "src/assets/Tacos/thon.jpg",
      originalPrice: "29.45DH",
      discountedPrice: "25.04DH",
    },
    {
      id: 5,
      title: "Tacos Mixtes",
      description: "Fresh Poulet, basil, and tomato sauce.",
      image: "src/assets/Tacos/mixtes.jpg",
      originalPrice: "40.45DH",
      discountedPrice: "35.04DH",
    },
  ],
  Lasagne: [
    {
      id: 1,
      title: "Lasagne SeaFood",
      description: "Fresh Plats, basil, and tomato sauce.",
      image: "src/assets/lasgne/seafood.jpg",
      originalPrice: "59.80DH",
      discountedPrice: "49.99DH",
    },
    {
      id: 2,
      title: "Lasagne Viande hacher",
      description: "Fresh Poulet, basil, and tomato sauce.",
      image: "src/assets/lasgne/viade hacher.jpg",
      originalPrice: "59.80DH",
      discountedPrice: "49.99DH",
    },
  ],
  Spa: [
    {
      id: 1,
      title: "Spagitti Bolognaise",
      description: "Fresh Plats, basil, and tomato sauce.",
      image: "src/assets/spagitti/bolognaise.jpeg",
      originalPrice: "35.80DH",
      discountedPrice: "29.99DH",
    },
    {
      id: 2,
      title: "Spagitti Poulet",
      description: "Fresh Poulet, basil, and tomato sauce.",
      image: "src/assets/spagitti/poulet.jpg",
      originalPrice: "35.80DH",
      discountedPrice: "29.99DH",
    },
    {
      id: 2,
      title: "Spagitti SeaFood",
      description: "Fresh Poulet, basil, and tomato sauce.",
      image: "src/assets/spagitti/seaFood.webp",
      originalPrice: "45.80DH",
      discountedPrice: "34.99DH",
    },
  ],
  Jus: [
    {
      id: 1,
      title: "Jus Orange",
      description: "Fresh Plats, basil, and tomato sauce.",
      image: "src/assets/jus/orange.jpeg",
      originalPrice: "19.80DH",
      discountedPrice: "14.99DH",
    },
    {
      id: 2,
      title: "Jus Banane",
      description: "Fresh Poulet, basil, and tomato sauce.",
      image: "src/assets/jus/banane.jpg",
      originalPrice: "19.80DH",
      discountedPrice: "14.99DH",
    },
    {
      id: 3,
      title: "Jus Pomme",
      description: "Fresh Poulet, basil, and tomato sauce.",
      image: "src/assets/jus/Pomme.jpeg",
      originalPrice: "19.80DH",
      discountedPrice: "14.99DH",
    },
    {
      id: 4,
      title: "Jus Avocat",
      description: "Fresh Poulet, basil, and tomato sauce.",
      image: "src/assets/jus/Avocat.jpeg",
      originalPrice: "25.80DH",
      discountedPrice: "19.99DH",
    },
    {
      id: 5,
      title: "Coktail Panacher",
      description: "Fresh Poulet, basil, and tomato sauce.",
      image: "src/assets/jus/Panache.jpg",
      originalPrice: "25.80DH",
      discountedPrice: "19.99DH",
    },
  ],
  Brouchette: [
    {
      id: 1,
      title: "Brouchette Viande hacher",
      description: "Fresh Plats, basil, and tomato sauce.",
      image: "src/assets/Brochette/plats-VH.jpg",
      originalPrice: "33.45DH",
      discountedPrice: "29.99DH",
    },
    {
      id: 2,
      title: "Brochette Poulet",
      description: "Fresh Poulet, basil, and tomato sauce.",
      image: "src/assets/Brochette/poulet1.jpg",
      originalPrice: "33.45DH",
      discountedPrice: "29.99DH",
    },
    {
      id: 3,
      title: "Brouchette Soucaisse",
      description: "Fresh Saucaisse, basil, and tomato sauce.",
      image: "src/assets/Brochette/Saucisse.webp",
      originalPrice: "33.45DH",
      discountedPrice: "29.99DH",
    },
    {
      id: 4,
      title: "Brochette Mixte",
      description: "Fresh mozzarella, basil, and tomato sauce.",
      image: "src/assets/Brochette/mixtes.avif",
      originalPrice: "42.05DH",
      discountedPrice: "35.99DH",
    },
  ],
};

export default MenuData;
